adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.UsersCreateView.as_view(), name='user_create'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    path('users/update/<int:pk>/',
         adminapp.UsersUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/',
         adminapp.UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', adminapp.category_create, name='category_create'),
    path('categories/read/', adminapp.categories, name='categories'),
    path('categories/update/<int:pk>/',
         adminapp.category_update, name='category_update'),
    path('categories/delete/<int:pk>/',
         adminapp.category_delete, name='category_delete'),

    path('products/create/category/<int:pk>/',
         adminapp.ProductCreateView.as_view(), name='product_create'),
    path('products/read/category/<int:pk>/',
         adminapp.ProductListView.as_view(), name='products'),
    path('products/read/<int:pk>/',
         adminapp.ProductDetailView.as_view(), name='product_read'),
    path('products/update/<int:pk>/',
         adminapp.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/',
         adminapp.ProductDeleteView.as_view(), name='product_delete'),
]

authapp/urls.py
from django.urls import path, re_path
from . import views


app_name = 'authapp'

urlpatterns = [
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('edit', views.edit, name='edit'),
    path('register', views.register, name='register'),
    re_path(
        r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', views.verify,
        name='verify'),
    
]

basketapp/urls.py
from django.urls import path
from . import views

app_name = 'basketapp'

urlpatterns = [
    path('', views.view, name='view'),
    path('add/<int:product_id>/', views.add, name='add'),
    path('remove/<int:basket_item_id>/', views.remove, name='remove'),
    path('edit/<int:basket_item_id>/<int:quantity>/', views.edit, name='edit'),

]

geekshop/mainapp/urls.py
from django.contrib import admin
from django.urls import path
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

urlpatterns = [

    path('', mainapp.products, name='main'),
    path('<int:category_id>/', mainapp.category, name='category'),
    path('<int:category_id>/<int:page>',
         mainapp.category, name='category_with_page'),
    path('product/<int:product_id>', mainapp.product, name='product'),
    path('product/<int:product_id>', mainapp.product, name='product')

    path('', mainapp.index, name='index'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contact/', mainapp.contact, name='contact'),
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
]

# Хостим папку media
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

geekshop/urls.py
from django.contrib import admin
from django.urls import path
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
from importlib import import_module
from django.urls import re_path

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('', mainapp.index, name='index'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contact/', mainapp.contact, name='contact'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('', include('social_django.urls', namespace='social')),
    re_path(r'^order/', include('ordersapp.urls', namespace='order')),
]

# Хостим папку media
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='main'),
    path('<int:category_id>/', mainapp.category, name='category'),
    path('<int:category_id>/<int:page>',
         mainapp.category, name='category_with_page'),
    path('product/<int:product_id>', mainapp.product, name='product'),
]

ordersapp/urls.py
import ordersapp.views as ordersapp
from django.urls import re_path, path

app_name = "ordersapp"

urlpatterns = [
    re_path(r'^$', ordersapp.OrderList.as_view(), name='orders_list'),
    re_path(r'^forming/complete/(?P<pk>\d+)/$',
            ordersapp.order_forming_complete, name='order_forming_complete'),
    re_path(r'^create/$', ordersapp.OrderItemsCreate.as_view(),
            name='order_create'),
    re_path(r'^read/(?P<pk>\d+)/$', ordersapp.OrderRead.as_view(),
            name='order_read'),
    re_path(r'^update/(?P<pk>\d+)/$', ordersapp.OrderItemsUpdate.as_view(),
            name='order_update'),
    re_path(r'^delete/(?P<pk>\d+)/$', ordersapp.OrderDelete.as_view(),
            name='order_delete'),
        path('product/<int:pk>/price/', ordersapp.product_price, name='product_price'),
]

mainapp/models.py
from unicodedata import name
from django.db import models

# Create your models here.


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)

    def __str__(self):
        return self.name


class ProductManager(models.Manager):
    def active_items(self):
        return Product.objects.filter(is_active=True)

class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    price = models.DecimalField(
        verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    color = models.IntegerField(verbose_name='цвет', default=0x000000)
    description = models.TextField(verbose_name='описание', blank=True)
    image = models.ImageField(upload_to='products_images', blank=True)
    quantity = models.PositiveIntegerField(
        verbose_name='количество на складе', default=0)
    is_active = models.BooleanField(verbose_name="активный", default=True)

    objects = ProductManager()

    def __str__(self):
        return self.name

mainapp/views.py
import json
from queue import Empty
from django.shortcuts import render, get_object_or_404
from .models import ProductCategory, Product
import random
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

# Create your views here.

def index(request):
    products = Product.objects.all()
    return render(request, 'mainapp/index.html', context={
        'title': 'главная',
        'products': products,

    })


def get_hot_product(queryset):
    return random.choice(queryset)


def products(request):
    categories = ProductCategory.objects.all()
    products = Product.objects.all()
    hot_product = get_hot_product(products)
    return render(request, 'mainapp/products.html', context={
        'title': 'продукты',
        'products': products.exclude(pk=hot_product.pk)[:4],
        'hot_product': hot_product,
        'categories': categories,
    })


def category(request, category_id, page=1):
    categories = ProductCategory.objects.all()
    category = get_object_or_404(ProductCategory, id=category_id)
    products = Product.objects.filter(category=category)
    hot_product = get_hot_product(products)

    # Определяем обьект paginator и передаем внутрь QwerySet и количество выводимых объектов
    paginator = Paginator(products.exclude(pk=hot_product.pk), 2)
    try:
        products_paginator = paginator.page(page)
    except PageNotAnInteger:
        products_paginator = paginator.page(1)
    except EmptyPage:
        products_paginator = paginator.page(paginator.num_pages)

    return render(request, 'mainapp/products.html', context={
        'title': 'продукты',
        'hot_product': get_hot_product(products),
        'products': products_paginator,
        'category': category,
        'categories': categories,
    })


def product(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    categories = ProductCategory.objects.all()
    return render(request, 'mainapp/product.html', context={
        'title': 'продукты',
        'product': product,
        'categories': categories,
    })


def contact(request):

    return render(request, 'mainapp/contact.html', context={
        'title': 'контакты',
    })

mainapp/templates/mainapp/includes/inc_categories_menu.html
<div class="links clearfix">
    <ul class="links-menu">
        <li><a href="{% url 'products:main' %}" 
            class="{% if request.resolver_match.view_name == 'products:main' %} active {% endif %}"
            >все</a></li>
        {% for category in categories %}
        <li><a href="{% url 'products:category' category.id %}" 
            class="{% if request.resolver_match.view_name == 'products:category' and request.resolver_match.kwargs.category_id == category.id %} active {% endif %}"
            >{{ category.name }}</a></li>
        {% endfor %}
    </ul>
</div>

mainapp/templates/mainapp/includes/inc_main_menu.html
<a href="{% url 'index' %}" class="logo"></a>
<ul class="menu">
    {% for link in menu_links %}
    <li>
        <a href="{% url link.url %}"
        class="{% if request.resolver_match.view_name in link.active %} active
        
        {% endif%}"
        >
        {{ link.name }}
    </a>
</li>
{% endfor %}
{% if user.is_authenticated %}
<li>
    <a href="{% url 'contact' %}" class="{% if request.resolver_match.url_name ==
        'contact' %}active{% endif %}">
    </a>
</li>
{% if user.is_authenticated %}
<li>
    <div class="dropdown">
        <a class="dropdown-toggle" href="" data-toggle="dropdown">
            {{ user.first_name|default:'Пользователь' }}
            <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
            <li class="dropdown-item">
                <a href="{% url 'auth:edit' %}">
                    профиль
                </a>
            </li>
            <li class="dropdown-item">
                <a href="{% url 'ordersapp:orders_list' %}">
                    заказы
                    </a>
                </li>
            </ul>
        </div>
    </li>
    {% endif %}
    {% if user.is_superuser %}
    <li>
        <a href="{% url 'admin:users' %}">админка</a>
    </li>
    {% endif %}
    {% if user.is_superuser %}
    <li>
        <a href="{% url 'admin:users' %}">
            Админка
        </a>
    </li>
    {% endif %}
    {% if user.is_authenticated %}
    <li>
        <a href="{% url 'basket:view' %}">корзина
            ({{ user.basket.total_cost }} руб.) ({{ user.basket.total_quantity }} шт.)
        </a>
    </li>
    {% endif%}
    <li>
        {% if user.is_authenticated %}
        <a href="{% url 'auth:logout' %}">выйти</a>
        {% else %}
        <a href="{% url 'auth:login' %}">войти</a>
        {% endif %}
    </li>
    
</li>

</ul>
<a href="#" class="search"></a>
<a href="#" class="basket"></a>

mainapp/templates/mainapp/includes/inc_products.html
{% if products %}
  {% if products.has_previous %}
  <a href="{% url 'products:category_with_page' category.pk products.previous_page_number %}"> сюда </a>
  {% endif %}
  страница {{ products.number }} из {{ products.paginator.num_pages }}
  {% if products.has_next %}
  <a href="{% url 'products:category_with_page' category.pk products.next_page_number %}"> туда</a>
  {% endif %}
{% endif %} 
{% for product in products %}
<div class="block">
  <a href="{% url 'products:product' product.id %}"
    ><img class="block" src="/media/{{ product.image }}" alt="" />
    <div class="text">
      <img src="/media/{{ product.image }}" alt="img" />
      <h4>{{ product.category.name }}</h4>
      <p>{{ product.category.description }}</p>
    </div>
  </a>
</div>
{% endfor %}