adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.UsersCreateView.as_view(), name='user_create'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    path('users/update/<int:pk>/',
         adminapp.UsersUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/',
         adminapp.UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', adminapp.category_create, name='category_create'),
    path('categories/read/', adminapp.categories, name='categories'),
    path('categories/update/<int:pk>/',
         adminapp.category_update, name='category_update'),
    path('categories/delete/<int:pk>/',
         adminapp.category_delete, name='category_delete'),

    path('products/create/category/<int:pk>/',
         adminapp.ProductCreateView.as_view(), name='product_create'),
    path('products/read/category/<int:pk>/',
         adminapp.ProductListView.as_view(), name='products'),
    path('products/read/<int:pk>/',
         adminapp.ProductDetailView.as_view(), name='product_read'),
    path('products/update/<int:pk>/',
         adminapp.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/',
         adminapp.ProductDeleteView.as_view(), name='product_delete'),
]

authapp/urls.py
from django.urls import path, re_path
from . import views


app_name = 'authapp'

urlpatterns = [
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('edit', views.edit, name='edit'),
    path('register', views.register, name='register'),
    re_path(
        r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', views.verify,
        name='verify'),
    
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
from importlib import import_module
from django.urls import re_path

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('', mainapp.index, name='index'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contact/', mainapp.contact, name='contact'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('', include('social_django.urls', namespace='social')),
    re_path(r'^order/', include('ordersapp.urls', namespace='order')),
]

# Хостим папку media
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from dataclasses import fields
from django import forms
from authapp.forms import ShopUserEditForm, ShopUserRegisterForm
from authapp.models import ShopUser
from mainapp.models import ProductCategory


class ShopUserEditAdminForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = '__all__'


class ShopUserCreateAdminForm(ShopUserRegisterForm):
    class Meta:
        model = ShopUser
        fields = '__all__'


class ProductCategoryAdminForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = '__all__'

# Так как используем bootstrap нужно это:


# def __init__(self, *args, **kwargs):
#     super().__init__(*args, **kwargs)
#     for field_name, field in self.field.items():
#         field.wiget.attrs['class'] = 'form_control'
#         field.help_text = ''

adminapp/views/category.py
from django.http.response import HttpResponseRedirect
from django.urls import reverse
from turtle import title
from django.shortcuts import get_object_or_404, render
from mainapp.models import ProductCategory
from adminapp.utils import superuser_requared
from adminapp.forms import ProductCategoryAdminForm


@superuser_requared
def category_create(request):
    title = 'Создание пользователя'

    if request.method == 'POST':
        form = ProductCategoryAdminForm(
            request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin:categories'))
    else:
        form = ProductCategoryAdminForm()

    return render(request, 'adminapp/category/edit.html', context={
        'form': form,
        'title': title,
    })


@superuser_requared
def categories(request):
    title = 'Категории'

    categories = ProductCategory.objects.all().order_by('id')

    return render(request, 'adminapp/category/categories.html', context={
        'title': title,
        'objects': categories,
    })


@superuser_requared
def category_update(request, pk):
    category = get_object_or_404(ProductCategory, pk=pk)
    title = 'Создание пользователя'

    if request.method == 'POST':
        form = ProductCategoryAdminForm(
            request.POST, instance=category)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin:categories'))
    else:
        form = ProductCategoryAdminForm(instance=category)

    return render(request, 'adminapp/category/edit.html', context={
        'form': form,
        'title': title,
    })


@superuser_requared
def category_delete(request):
    pass

adminapp/views/product.py
from pyexpat import model
from turtle import title
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from mainapp.models import Product, ProductCategory
from adminapp.utils import superuser_requared
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.utils.decorators import method_decorator
from adminapp.utils import superuser_requared
from django.views.generic.detail import DetailView


# Create Product in Category
class ProductCreateView(CreateView):
    model = Product
    fields = '__all__'  # Django makes form auto
    template_name = 'adminapp/product/edit.html'

    @method_decorator(superuser_requared)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_initial(self):
        return {
            'category': self.get_category()
        }

    def get_success_url(self):
        return reverse('admin:products', kwargs=self.kwargs)

    def get_category(self):
        return ProductCategory.objects.get(pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = ProductCategory.objects.get(pk=self.kwargs['pk'])
        return context


class ProductListView(ListView):
    model = Product
    template_name = 'adminapp/product/products.html'

    @method_decorator(superuser_requared)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_initial(self):
        return {
            'category': self.get_category(),
            'product': self.get_product()
        }

    def get_category(self):
        return ProductCategory.objects.get(pk=self.kwargs['pk'])

    def get_product(self):
        return Product.objects.get(pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        category = get_object_or_404(ProductCategory, pk=self.kwargs['pk'])
        products = Product.objects.filter(
            category=category).order_by('id')
        context = super().get_context_data(**kwargs)
        context = {
            'category': category,
            'objects': products
        }
        return context


class ProductDetailView(DetailView):
    model = Product
    template_name = 'adminapp/product/product_read.html'


class ProductUpdateView(UpdateView):
    model = Product
    template_name = 'adminapp/product/product_updata.html'
    success_url = reverse_lazy('admin:users')
    fields = '__all__'


class ProductDeleteView(DeleteView):
    model = Product
    template_name = 'adminapp/product/product_delete.html'
    success_url = reverse_lazy('admin:products')

    def Delete(self, request, *args, **kwarga):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())

adminapp/views/user.py
from django.http.response import HttpResponseRedirect
from turtle import title
from django.shortcuts import render, get_object_or_404
from authapp.models import ShopUser
from adminapp.utils import superuser_requared
from adminapp.forms import ShopUserCreateAdminForm, ShopUserEditAdminForm
from django.urls import reverse, reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.utils.decorators import method_decorator


class UsersCreateView(CreateView):
    model = ShopUser
    form_class = ShopUserCreateAdminForm
    template_name = 'adminapp/user/edit.html'
    success_url = reverse_lazy('admin:users')

    @method_decorator(superuser_requared)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


# Changed users_view on CBV


class UsersListView(ListView):
    model = ShopUser
    template_name = 'adminapp/user/users.html'

    @method_decorator(superuser_requared)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class UsersUpdateView(UpdateView):
    model = ShopUser
    form_class = ShopUserEditAdminForm
    template_name = 'adminapp/user/edit.html'
    success_url = reverse_lazy('admin:users')

    @method_decorator(superuser_requared)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Редактирование пользователя'

        return context


class UserDeleteView(DeleteView):
    model = ShopUser
    template_name = 'adminapp/user/delete.html'
    success_url = reverse_lazy('admin:users')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Удаление пользователя'

        return context

adminapp/templates/adminapp/product/edit.html
{% extends 'adminapp/base.html' %} {% load static %} {% block content %}
<form class="form-horizontal" method="post" enctype="multipart/form-data">
  {% csrf_token %} {{ form.as_p }}
  <input class="form-control" type="submit" value="сохранить" />
</form>
<button class="btn btn-round form-control last">
  <a href="{% url 'admin:products' category.pk %}"> к списку товаров </a>
</button>
{% endblock %}

adminapp/templates/adminapp/product/product_delete.html
{% extends 'basketapp/base.html' %} {% load static %} {% block js %}
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/basket_scripts.js' %}"></script>
{% endblock %} {% block content %}
<div class="basket_list">
  {% include 'basketapp/includes/inc_basket_list.html' %}
</div>

<button class="btn btn-round">
  <a href="{% url 'index' %}">на главную</a>
</button>
{% endblock %}

adminapp/templates/adminapp/product/product_read.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="product_read">
    <div class="product_name">
        Продукт<strong>{{ object.category.name|title }} /
            {{ object.name|title }}</strong>
        </div>
        <img src="/media/{{ object.image|default:'products_images/default.jpg' }}"
        alt="{{ object.name }}">
        <div class="summary">
            <b>цена</b>
            <p>{{ object.price }} руб</p>
            <b>количество</b>
            <p>{{ user.basket.total_quantity }}</p>
            <b>в каталоге</b>
            <p>{% if object.is_active %}да{% else %}нет{% endif %}</p>
            <p>
                <button>
                    <a href={% url 'admin:product_update' object.pk %}>
                        редактировать
                    </a>
                </button>
            </p>
            <p>
                <button>
                    <a href={% url 'admin:product_delete' object.pk %}>
                        удалить
                    </a>
                </button>
            </p>
            <p>
                <button>
                    <a href={% url 'admin:products' object.category.pk %}>
                        назад
                    </a>
                </button>
            </p>
        </div>
        <div class="product_desc">
            <b>краткая информация</b>
            <p>{{ object.short_desc }}</p>
            <br><br>
            <b>подробная информация</b>
            <p>{{ object.description }}</p>
        </div>
    </div>
    {% endblock %}

adminapp/templates/adminapp/product/product_updata.html
{% extends 'adminapp/base.html' %} {% load static %} {% block content %}
<form class="form-horizontal" method="post" enctype="multipart/form-data">
  {% csrf_token %} {{ form.as_p }}
  <input class="form-control" type="submit" value="сохранить" />
</form>
<button class="btn btn-round form-control last">
  <a href="{% url 'admin:products' product.pk %}"> к списку товаров </a>
</button>
{% endblock %}

adminapp/templates/adminapp/product/products.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="products_list">
    <button class="new_product">
        <a href={% url 'admin:product_create' category.pk %}>
            новый продукт
        </a>
    </button>
    {% for object in objects %}
    <div class="product_record">
        <img
        src="/media/{{object.image|default:'products_images/default.jpg'}}"
        alt="{{ object.name }}">
        <div class="product_name">
            {{ object.name|title }}
        </div>
        <div class="product_actions">
            <button>
                <a href={% url 'admin:product_read' object.pk %}>
                    подробнее
                </a>
            </button>
            <button>
                <a href={% url 'admin:product_update' object.pk %}>
                    редактировать
                </a>
            </button>
            <button>
                <a href={% url 'admin:product_delete' object.pk %}>
                    удалить
                </a>
            </button>
        </div>
        <div class="summary">
            <b>цена</b>
            <p>{{ object.price }} руб</p>
            <b>количество</b>
            <p>{{ object.quantity }}</p>
        </div>
        <div class="product_desc">
            {{ object.short_desc|title }}
        </div>
    </div>
    {% endfor%}
</div>
{% endblock %}