authapp/urls.py
from django.urls import path, re_path
from . import views


app_name = 'authapp'

urlpatterns = [
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('edit', views.edit, name='edit'),
    path('register', views.register, name='register'),
    re_path(
        r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', views.verify,
        name='verify'),
    
]

basketapp/urls.py
from django.urls import path
from . import views

app_name = 'basketapp'

urlpatterns = [
    path('', views.view, name='view'),
    path('add/<int:product_id>/', views.add, name='add'),
    path('remove/<int:basket_item_id>/', views.remove, name='remove'),
    path('edit/<int:basket_item_id>/<int:quantity>/', views.edit, name='edit'),

]

geekshop/mainapp/urls.py
from django.contrib import admin
from django.urls import path
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

urlpatterns = [

    path('', mainapp.products, name='main'),
    path('<int:category_id>/', mainapp.category, name='category'),
    path('<int:category_id>/<int:page>',
         mainapp.category, name='category_with_page'),
    path('product/<int:product_id>', mainapp.product, name='product'),
    path('product/<int:product_id>', mainapp.product, name='product')

    path('', mainapp.index, name='index'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contact/', mainapp.contact, name='contact'),
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
]

# Хостим папку media
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

geekshop/urls.py
from django.contrib import admin
from django.urls import path
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
from importlib import import_module
from django.urls import re_path

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('', mainapp.index, name='index'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contact/', mainapp.contact, name='contact'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('', include('social_django.urls', namespace='social')),
    re_path(r'^order/', include('ordersapp.urls', namespace='order')),
]

# Хостим папку media
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='main'),
    path('<int:category_id>/', mainapp.category, name='category'),
    path('<int:category_id>/<int:page>',
         mainapp.category, name='category_with_page'),
    path('product/<int:product_id>', mainapp.product, name='product'),
]

mainapp/models.py
from unicodedata import name
from django.db import models

# Create your models here.


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)

    def __str__(self):
        return self.name


class ProductManager(models.Manager):
    def active_items(self):
        return Product.objects.filter(is_active=True)

class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    price = models.DecimalField(
        verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    color = models.IntegerField(verbose_name='цвет', default=0x000000)
    description = models.TextField(verbose_name='описание', blank=True)
    image = models.ImageField(upload_to='products_images', blank=True)
    quantity = models.PositiveIntegerField(
        verbose_name='количество на складе', default=0)
    is_active = models.BooleanField(verbose_name="активный", default=True)

    objects = ProductManager()

    def __str__(self):
        return self.name

adminapp/views/product.py
from pyexpat import model
from turtle import title
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from mainapp.models import Product, ProductCategory
from adminapp.utils import superuser_requared
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.utils.decorators import method_decorator
from adminapp.utils import superuser_requared
from django.views.generic.detail import DetailView


# Create Product in Category
class ProductCreateView(CreateView):
    model = Product
    fields = '__all__'  # Django makes form auto
    template_name = 'adminapp/product/edit.html'

    @method_decorator(superuser_requared)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_initial(self):
        return {
            'category': self.get_category()
        }

    def get_success_url(self):
        return reverse('admin:products', kwargs=self.kwargs)

    def get_category(self):
        return ProductCategory.objects.get(pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = ProductCategory.objects.get(pk=self.kwargs['pk'])
        return context


class ProductListView(ListView):
    model = Product
    template_name = 'adminapp/product/products.html'

    @method_decorator(superuser_requared)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_initial(self):
        return {
            'category': self.get_category(),
            'product': self.get_product()
        }

    def get_category(self):
        return ProductCategory.objects.get(pk=self.kwargs['pk'])

    def get_product(self):
        return Product.objects.get(pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        category = get_object_or_404(ProductCategory, pk=self.kwargs['pk'])
        products = Product.objects.filter(
            category=category).order_by('id')
        context = super().get_context_data(**kwargs)
        context = {
            'category': category,
            'objects': products
        }
        return context


class ProductDetailView(DetailView):
    model = Product
    template_name = 'adminapp/product/product_read.html'


class ProductUpdateView(UpdateView):
    model = Product
    template_name = 'adminapp/product/product_updata.html'
    success_url = reverse_lazy('admin:users')
    fields = '__all__'


class ProductDeleteView(DeleteView):
    model = Product
    template_name = 'adminapp/product/product_delete.html'
    success_url = reverse_lazy('admin:products')

    def Delete(self, request, *args, **kwarga):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())

mainapp/views.py
import json
from queue import Empty
from django.shortcuts import render, get_object_or_404
from .models import ProductCategory, Product
import random
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

# Create your views here.

def index(request):
    products = Product.objects.all()
    return render(request, 'mainapp/index.html', context={
        'title': 'главная',
        'products': products,

    })


def get_hot_product(queryset):
    return random.choice(queryset)


def products(request):
    categories = ProductCategory.objects.all()
    products = Product.objects.all()
    hot_product = get_hot_product(products)
    return render(request, 'mainapp/products.html', context={
        'title': 'продукты',
        'products': products.exclude(pk=hot_product.pk)[:4],
        'hot_product': hot_product,
        'categories': categories,
    })


def category(request, category_id, page=1):
    categories = ProductCategory.objects.all()
    category = get_object_or_404(ProductCategory, id=category_id)
    products = Product.objects.filter(category=category)
    hot_product = get_hot_product(products)

    # Определяем обьект paginator и передаем внутрь QwerySet и количество выводимых объектов
    paginator = Paginator(products.exclude(pk=hot_product.pk), 2)
    try:
        products_paginator = paginator.page(page)
    except PageNotAnInteger:
        products_paginator = paginator.page(1)
    except EmptyPage:
        products_paginator = paginator.page(paginator.num_pages)

    return render(request, 'mainapp/products.html', context={
        'title': 'продукты',
        'hot_product': get_hot_product(products),
        'products': products_paginator,
        'category': category,
        'categories': categories,
    })


def product(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    categories = ProductCategory.objects.all()
    return render(request, 'mainapp/product.html', context={
        'title': 'продукты',
        'product': product,
        'categories': categories,
    })


def contact(request):

    return render(request, 'mainapp/contact.html', context={
        'title': 'контакты',
    })

mainapp/templates/mainapp/base.html
{% load static %}

<html>
<head>
	<meta charset="utf-8">
	<title>{{ title }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/css/font-awesome.css' %}">
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>

<body>
	<div class="container">

        {% block header %}
            HEAD
        {% endblock %}

        {% block content %}
		    CONTENT
        {% endblock %}

		<div class="clr"></div>
	</div>	

    <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB {% now "Y" %}</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
    </div>	
			
</body>
</html>

mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}

{% block header %}
<div class="hero">
	<div class="header clearfix">
		{% include 'mainapp/includes/inc_main_menu.html' %}
	</div>
	<h1>наши контакты</h1>
</div>
{% endblock %}

{% block content %}
<div class="location">
	<div class="location-1">
		<i class="fa fa-map-marker fa-5x"></i>
		<h4>Москва</h4>
		<div class="contacts">
			<h5>Телефон</h5>
			<p>+7-888-888-8888</p>
		</div>
		<div class="contacts">
			<h5>Email</h5>
			<p>info@geekshop.ru</p>
		</div>
		<div class="contacts">
			<h5>Адрес</h5>
			<p>В пределах МКАД</p>
		</div>
	</div>
	<div class="location-1">
		<i class="fa fa-map-marker fa-5x"></i>
		<h4>Москва</h4>
		<div class="contacts">
			<h5>Телефон</h5>
			<p>+7-888-888-8888</p>
		</div>
		<div class="contacts">
			<h5>Email</h5>
			<p>info@geekshop.ru</p>
		</div>
		<div class="contacts">
			<h5>Адрес</h5>
			<p>В пределах МКАД</p>
		</div>
	</div>
	<div class="location-1">
		<i class="fa fa-map-marker fa-5x"></i>
		<h4>Москва</h4>
		<div class="contacts">
			<h5>Телефон</h5>
			<p>+7-888-888-8888</p>
		</div>
		<div class="contacts">
			<h5>Email</h5>
			<p>info@geekshop.ru</p>
		</div>
		<div class="contacts">
			<h5>Адрес</h5>
			<p>В пределах МКАД</p>
		</div>
	</div>
</div>
{% endblock %}

		

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block header %}
<div class="slider">
	<div class="header clearfix">
		{% include 'mainapp/includes/inc_main_menu.html' %}
	</div>
	<div class="text-slider">
		<h3 class="green">тенденции</h3>
		<h3 class="big"> удобные стулья</h3>
		<p>Новый уровень комфорта. Отличные характеристики.</p>
		<a href="#" class="button-order">заказать <img src="{% static 'img/arrow.png' %}" alt=""></a>
	</div>	
	<div class="navi">
		<a href="#"></a><a href="#"></a><a href="#"></a>
	</div>
</div>
{% endblock %}

{% block content %}
<div class="featured">
	<div class="featured-menu">
		<a class="active" href="#">Популярные</a><a href="#">Новинки</a>
	</div>
		<a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
	<div class="clearfix">
	</div>
	<div class="tab-content">
		{% include 'mainapp/includes/inc_products.html' %}
	</div>
</div>
{% endblock %}
		

mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block header %}
<div class="hero-white">
	<div class="header clearfix">
		{% include 'mainapp/includes/inc_main_menu.html' %}
	</div>
</div>
{% endblock %}

{% block content %}
<div class="details">
	{% include 'mainapp/includes/inc_categories_menu.html' %}

	{% if product %}
	<div class="details-products">
		<div class="details-slider">
			<div class="slider-product">
				<img src="{{ product.image.url }}">
			</div>
		</div>
	{% endif %}

		<div class="description">
			<h3 class="big-bold">{{ product.name }}</h3>
			<h3 class="red">горячее предложение</h3>
			<p class="price"> {{ product.price }} <span>руб</span></p>
			<a href="{% url 'basket:add' product.id %}" class="red-button">
				заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
			</a>
			<div class="description-text">
				{{ product.description|linebreaks }}
			</div>
		</div>
	</div>
</div>
{% endblock %}
		

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block header %}
<div class="hero-white">
	<div class="header clearfix">
		{% include 'mainapp/includes/inc_main_menu.html' %}
	</div>
</div>
{% endblock %}

{% block content %}
<div class="details">
	{% include 'mainapp/includes/inc_categories_menu.html' %}

	{% if hot_product %}
	<div class="details-products">
		<div class="details-slider">
			<div class="slider-product">
				<img src="{{ hot_product.image.url }}">
			</div>
		</div>
	{% endif %}

		<div class="description">
			<h3 class="big-bold">{{ hot_product.name }}</h3>
			<h3 class="red">горячее предложение</h3>
			<p class="price"> {{ hot_product.price }} <span>руб</span></p>
			<a href="{% url 'basket:add' hot_product.id %}" class="red-button">
				заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
			</a>
			<div class="description-text">
				{{ hot_product.description|linebreaks }}
			</div>
		</div>
	</div>

	{% if products %}
	<div class="related">
		<div class="title clearfix">
			<h2>Похожие продукты</h2>
			<a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
		</div>
		<div class="related-products clearfix">
			{% include 'mainapp/includes/inc_products.html' %}
		</div>
	</div>
	{% endif %}
</div>
{% endblock %}
		